### ISSUE TITLE
toJSON() is not a fuction for a complex object.

### ISSUE THREAD

**Issue by g-guth** [RSuter/NSwag#864]
Hi, im using the great tool NSWAG with my angular4 app but having a problem with an object cast:

> UPDATE: This error starts to occour when I updated from version "nswag": "^8.8.0" to version "nswag": "10.6.0"

In my C# Code i have this class:

```
 public class CreateTestDto
 {
          public string Name { get; set; }
          public TestDto Test { get; set; }
 }
```

```
public class TestDto 
{
      public string Description { get; set; }
}`
```

Then in my Angular4 form Component:

```
  this.createTest= new CreateTestDto(<CreateTestDto>this.formTest.root.value);
  this.testService.create(this.createTest).subscribe();
```

The auto-generated nswag code (testService):

``` 
     create(createTest: CreateTestDto):  void {
        let url_ = this.baseUrl + "/api/services/CreateTest";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(createTest? createTest.toJSON() : null);
      /// etc
```

On the create method it throws an error when it tries to execute `createTest.toJSON()`, saing:

> this.test.toJSON is not a function. 

It seems that when i cast to the `createTest ` object, only the `CreateTestDto` gets the `__proto__` with the `toJSON()` method, but the inner `TestDto` property doesnt, it only maps the `Description` property and the `__proto__` is of type `Object`.

**Comment by RSuter** [comment]
The parameter of `CreateTestDto` is of type `ICreateTestDto` but the properties are not of the interface but require the correct instances, so you need to `new ...` them too... The properties are just copied into the new instance and thus must be of the correct type (cannot be POJOs)

**Comment by g-guth** [comment]
Why it was working on ^8.8.0 version?

**Comment by RSuter** [comment]
Ah, yes the behavior has changed, as a hack you can use

    let x = new CreateTestDto();
    x.init(<CreateTestDto>this.formTest.root.value);

but the expected parameter of init() (and the previous ctor) is not the POJO version of the class but the data of the server (i.e. the casing may be different, etc...)

**Comment by RSuter** [comment]
I think this might interest you: https://github.com/RSuter/NJsonSchema/issues/494
